
MAX(IF(Дата=DATETIME_SUB(DATETIME_TRUNC(CURRENT_DATETIME("Europe/Moscow"), HOUR), INTERVAL 0 DAY), Дата,IF(Дата=DATETIME_SUB(DATETIME_TRUNC(CURRENT_DATETIME("Europe/Moscow"), HOUR), INTERVAL 1 HOUR), NULL))
